### ISSUE TITLE
Negative dimensions error when running Cormier algorithm

### ISSUE THREAD

**Issue by vkhangpham** [webis-de/ecir21-an-empirical-comparison-of-web-page-segmentation-algorithms#3]
## Error

Hi, I got the error below when try to run the algorithm of Cormier

```
Traceback (most recent call last):
  File "/home/vkhangpham/Projects/wps-algos/algorithms/cormier/cormier.py", line 254, in <module>
    s_list, pic = segment(args.image)
  File "/home/vkhangpham/Projects/wps-algos/algorithms/cormier/cormier.py", line 142, in segment
    segment_list = segment_rec(horiz, vert, 0, 0, len(horiz), 0, len(horiz[0])).to_list()
  File "/home/vkhangpham/Projects/wps-algos/algorithms/cormier/cormier.py", line 194, in segment_rec
    self.children.append(segment_rec(h, v, level + 1, start, end, l, r, dir_v))
  File "/home/vkhangpham/Projects/wps-algos/algorithms/cormier/cormier.py", line 153, in segment_rec
    h_prob, v_prob = np.ones(len(h_curr) - min_l * 2, dtype='float'), np.ones(len(v_curr) - min_l * 2, dtype='float')
  File "/home/vkhangpham/miniconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 204, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed
```
## System

OS: Ubuntu 20.04 LTS
Python: 3.9.12
Numpy: 1.22.3
R: 4.2.1

## Reproduce

To reproduce, run the code from [Cormier et al.](https://github.com/webis-de/ecir21-an-empirical-comparison-of-web-page-segmentation-algorithms#cormier-et-al) section.

**Comment by johanneskiesel** [comment]
Thanks for reporting! I was able to reproduce the error in Python 3.8.10, numpy 1.20.1.

```
...
cdf row 5588
cdf row 5589
(array([6415041,  530720,  204847,  112353,   78022,   44897,   38954,
         23202,   24361,   17482,   15576,    7267,   14754,   12477,
          5616,    3047,   67737,    7252,    3651,    8684]), array([0.03942458, 0.08460078, 0.12977697, 0.17495317, 0.22012936,
       0.26530556, 0.31048175, 0.35565795, 0.40083414, 0.44601034,
       0.49118653, 0.53636273, 0.58153892, 0.62671512, 0.67189131,
       0.71706751, 0.7622437 , 0.8074199 , 0.85259609, 0.89777229,
       0.94294848]))
0 0 5590 0 1366 None
1 0 25 0 1366 1
Traceback (most recent call last):
  File "algorithms/cormier/cormier.py", line 254, in <module>
    s_list, pic = segment(args.image)
  File "algorithms/cormier/cormier.py", line 142, in segment
    segment_list = segment_rec(horiz, vert, 0, 0, len(horiz), 0, len(horiz[0])).to_list()
  File "algorithms/cormier/cormier.py", line 194, in segment_rec
    self.children.append(segment_rec(h, v, level + 1, start, end, l, r, dir_v))
  File "algorithms/cormier/cormier.py", line 153, in segment_rec
    h_prob, v_prob = np.ones(len(h_curr) - min_l * 2, dtype='float'), np.ones(len(v_curr) - min_l * 2, dtype='float')
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/numeric.py", line 203, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed
```

Likely the behavior of `ones` changes. I'll take a look.

**Comment by johanneskiesel** [comment]
I fixed a bug in the code in this regard. In prior versions, it seems that NumPy handled a negative value to `ones` graciously whereas now it throws an error.

The segmentations I get now are slightly different, maybe related to other changes in the libraries. But the software itself should be fine once more.

However, Michael (Cormier) had also been working on publishing an own version of his algorithm (the code here is just his experimental code that he thankfully send us as we could not wait). You might want to ask him if he published it somewhere in the meantime.

I am closing this. Please re-open if it is not solved for you.

**Comment by vkhangpham** [comment]
It works now, thank you for the informative response
